
version: '3.8'

services:
  quiz-app:
    image: node:18-alpine
    container_name: insightful-assessment-engine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: >
      sh -c "npm ci --omit=dev &&
             npm run build &&
             npm run preview"
    restart: unless-stopped
    depends_on:
      - supabase-db

  supabase-db:
    image: supabase/postgres:14.1.0
    container_name: quiz-supabase-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
