
version: '3.8'

services:
  quiz-app:
    image: node:18-alpine
    container_name: insightful-assessment-engine
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=production
    command: >
      sh -c "npm ci --omit=dev &&
             npm run build &&
             npm run preview"
    restart: unless-stopped
    depends_on:
      - supabase-db
    # Removida a exposição direta da porta 3000, pois o nginx lidará com isso

  nginx:
    image: nginx:alpine
    container_name: quiz-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    environment:
      - DOMAIN=seudominio.com.br
    restart: unless-stopped
    depends_on:
      - quiz-app

  supabase-db:
    image: supabase/postgres:14.1.0
    container_name: quiz-supabase-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
