// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xymifpahvgaexrfwjzrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5bWlmcGFodmdhZXhyZndqenJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2OTY4MzAsImV4cCI6MjA2MTI3MjgzMH0.tUHBsOEJEjYgurnq_yBC744LnJYhBOm-TnLSS6Hr8C0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);